### PR TITLE
Buggy update

### PR DESCRIPTION
**Pull request by Adedayo99**
The code is now in a scalable form. The only    bugs present is that the function does not print newline if the newline character is placed at the end of the format string. It prints the new line character everywhere else.
Am trying to resolve that.

### CODE REVIEW

**Review by Adedayo99 — COMMENTED** [review]
I feel so proud right now! Am excited to be learning how to not just write code but design good software!

**Comment by Adedayo99** [comment]
Added implementation for %d and %i. Both are working fine

**Review by Adedayo99 — COMMENTED** [review]
Just fine

**Review by NnaemekaAlgorithim — COMMENTED** [review]
Nice work!

**Review by NnaemekaAlgorithim — APPROVED** [review]
Cool!

**Pull request merged**
